### ISSUE TITLE
Missing attribute service.name when using instrumentation net/http through opentelemetry collector.

### ISSUE THREAD

**Issue by firefixmaarten** [open-telemetry/opentelemetry-go-contrib#249]
Related to:
https://github.com/open-telemetry/opentelemetry-collector/issues/1385#issuecomment-664525162

using the following code:
```
package main

import (
	"context"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"net/http"
	"time"

	otelhttp "go.opentelemetry.io/contrib/instrumentation/net/http"
	"google.golang.org/grpc"

	"go.opentelemetry.io/otel/api/correlation"
	"go.opentelemetry.io/otel/api/global"
	"go.opentelemetry.io/otel/api/kv"
	"go.opentelemetry.io/otel/api/standard"
	"go.opentelemetry.io/otel/api/trace"
	"go.opentelemetry.io/otel/exporters/otlp"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func initTracer() {
	exporter, err := otlp.NewExporter(
		otlp.WithInsecure(),
		otlp.WithAddress("localhost:55681"),
		otlp.WithGRPCDialOption(grpc.WithBlock()),
	)
	if err != nil {
		log.Fatal(err)
	}

	tp, err := sdktrace.NewProvider(sdktrace.WithConfig(
		sdktrace.Config{DefaultSampler: sdktrace.AlwaysSample()}),
		sdktrace.WithResource(resource.New(standard.ServiceNameKey.String("client-test"))),
		sdktrace.WithSyncer(exporter),
	)
	global.SetTraceProvider(tp)

}

func main() {
	initTracer()
        url := flag.String("server", "https://testendpoint.local", "server url")
	flag.Parse()

	client := http.Client{Transport: otelhttp.NewTransport(http.DefaultTransport)}

	ctx := correlation.NewContext(context.Background(),
		kv.String("identifier", "maarten-12346"),
	)

	var body []byte

	tr := global.Tracer("")

	host, err := os.Hostname()
	if err != nil {
		log.Fatal(err)
	}

	err = tr.WithSpan(ctx, "GetClusterInfo",
		func(ctx context.Context) error {
			req, _ := http.NewRequestWithContext(ctx, "GET", *url, nil)

			fmt.Printf("Sending request...\n")
			res, err := client.Do(req)
			if err != nil {
				panic(err)
			}
			body, err = ioutil.ReadAll(res.Body)
			_ = res.Body.Close()

			return err
		},
		trace.WithAttributes(standard.HostNameKey.String(host)),
	)

	if err != nil {
		panic(err)
	}

	fmt.Printf("Response Received: %s\n\n\n", body)
	fmt.Printf("Waiting for few seconds to export spans ...\n\n")
	time.Sleep(60 * time.Second)
}
```
go.mod:
```
	go.opentelemetry.io/contrib/instrumentation/net/http v0.10.1
	go.opentelemetry.io/otel v0.10.0
	go.opentelemetry.io/otel/exporters/otlp v0.10.0
	go.opentelemetry.io/otel/sdk v0.10.0
```
OTel collector is version 0.8.0.
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55681

exporters:
  jaeger:
    endpoint: localhost:14250
    insecure: true

processors:
  batch:
  queued_retry:
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger]
```
This results in an empty ServiceName field in jaeger => making the UI less usefull
 ```
"processes": {
        "p1": {
          "serviceName": "",
          "tags": [
            {
              "key": "host.name",
              "type": "string",
              "value": "fr1-outpost"
            }
          ]
        }
```

Are we on OTLP protocol 0.4.0 or a older version for this instrumentation net/http ?
https://github.com/open-telemetry/opentelemetry-collector/blob/18409e165fa668acb2942d4d06b96b2053ae5f79/translator/trace/jaeger/traces_to_jaegerproto.go#L107 <= do we use the new value attribute already ?

**Comment by XSAM** [comment]
I run this code in my local machine but cannot reproduce this issue.

<details>
<summary>go.mod</summary>

```
go.opentelemetry.io/contrib/instrumentation/net/http v0.10.1
go.opentelemetry.io/otel/exporters/otlp v0.10.0
```
</details>

<details>
<summary>docker-compose.yaml</summary>

```
version: "2.4"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - 14250:14250
      - 16686:16686
    networks:
      - example
  otel-agent:
    image: otel/opentelemetry-collector:0.8.0
    ports:
      - 55681:55681
      - 55679:55679
    command:
      - "/otelcol"
      - "--config=/conf/otel_agent_config.yaml"
    volumes:
      - ./otel_agent_config.yaml:/conf/otel_agent_config.yaml
    networks:
      - example

networks:
  example:
```
</details>

<details>
<summary>Environment</summary>

```
Golang 1.15
```
</details>
