### ISSUE TITLE
Request to Add Detector for Kubernetes

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go-contrib#4136]
## Background

At one point, I had written an OTep about how kubernetes resource detectors should function, but it wasn't accepted due to lack of interest. https://github.com/open-telemetry/oteps/pull/195

I was recently reminded of the impact of this in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2310#issuecomment-1665703221.

## Proposed Solution

Add a Kubernetes resource detector in detectors/kubernetes/.  It will have a single implementation of the resource.Detector interface, and no configuration.

It will detect:

* k8s.container.name
* k8s.pod.name
* k8s.pod.uid
* k8s.namespace.name
* k8s.node.name

From:

* OTEL_RESOURCE_ATTRIBUTES_K8S_CONTAINER_NAME
* OTEL_RESOURCE_ATTRIBUTES_K8S_POD_NAME
* OTEL_RESOURCE_ATTRIBUTES_K8S_POD_UID
* OTEL_RESOURCE_ATTRIBUTES_K8S_NAMESPACE_NAME
* OTEL_RESOURCE_ATTRIBUTES_K8S_NODE_NAME

If pod name is not discovered, fall back to the HOSTNAME env var.  This defaults to the pod's name, but can be overridden in the pod spec.

If pod namespace is not discovered, fall back to reading `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.  This is always the pod's namespace AFAIK, but isn't a recommended way to get it.

### Prior Art

OTel Operator: https://github.com/open-telemetry/opentelemetry-operator/blob/76cff59b0c0640da29c56d5ae91eae5fe843ae5b/pkg/constants/env.go#L25

## Tasks

- Code complete:
  - [ ] Comprehensive unit tests.
  - [ ] End-to-end integration tests.
  - [ ] Tests all passing.
  - [ ] Instrumentation functionality verified.
- Documented
  - [ ] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [ ] README included for the module describing high-level purpose.
  - [ ] Complete documentation of all public API including package documentation.
  - [ ] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [ ] `Dockerfile` file to build example application.
  - [ ] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.

@jaredjenkins

**Comment by dashpole** [comment]
Lets make sure maintainers are on-board first.

@open-telemetry/go-approvers please let me know if there are any objections to the proposed new component.  I'm happy to maintain it long-term.  It might be a good idea to have this in the spec first.

**Comment by MrAlias** [comment]
SGTM :+1:

**Comment by dashpole** [comment]
@anuraaga curious if you have feedback on the design above

**Comment by aabmass** [comment]
@dashpole should we introduce this to the spec? I don't think it should block this issue, but I would love to see a unified approach across all languages

**Comment by anuraaga** [comment]
Thanks @dashpole - for reference, here is my manifest config

```
        - name: OTEL_RESOURCE_K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OTEL_RESOURCE_K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_K8S_CONTAINER_NAME
          valueFrom:
            fieldRef:
              # With our kustomization config, deployment name is always
              # same as container name, a pod otherwise has no way to
              # reference it.
              fieldPath: metadata.labels['deployment']
        - name: OTEL_RESOURCE_K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "k8s.namespace.name=$(OTEL_RESOURCE_K8S_NAMESPACE_NAME),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_K8S_POD_NAME),k8s.container.name=$(OTEL_RESOURCE_K8S_CONTAINER_NAME),k8s.deployment.name=$(OTEL_RESOURCE_K8S_DEPLOYMENT_NAME)"
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
```

(btw, I couldn't find a way to get container name with downstream API though I notice this issue description mentions it, wonder if I missed it)

This is indeed pretty annoying :) IIUC, the proposal would remove that OTEL_RESOURCE_ATTRIBUTES gnarly line, which is an improvement. However, I don't know how much of an improvement it is, skimming through the OTEP I saw one motivation is to have a copy-pastable snippet to get these filled. Unfortunately, the most important attribute `service.name` cannot be copy-pasted, so in the end there will be thinking required by the user. Similar for k8s.container.name, which while not as important, from what I've seen as a GCP user it does seem to be used in the UI in the tree navigation, so presumably is better to fill than not.

Another issue is while the OTEP mentioned issues with merge and telemetry schema related to the `OTEL_RESOURCE_ATTRIBUTES` variable, in practice I don't know if that variable is avoidable anyways, for example while my snippet doesn't have it yet, my next update will be adding the highly useful `service.version`, meaning I'm stuck with it anyways - at that point, it doesn't hurt much to have the k8s fields there as well.

So to sum up - if this detector existed, I would take advantage of the simplification by tweaking the variable names, which would be an improvement, but IMO not a big one. Given that this would need to be implemented in all the languages, there does seem to be low bang for the relatively large effort. As a user, personally I would be much happier if manpower, which I presume isn't unlimited, was spent on making sure all the instrumentation records metrics and more complete support for the SDK environment variables as while the variable setting is awkward, it's doable.
