### ISSUE TITLE
autoexport: No support for env var expansion

### ISSUE THREAD

**Issue by douglascamata** [open-telemetry/opentelemetry-go-contrib#6830]
### Description

Environment variable expansion is not being done by the `autoexport` package, which breaks already existing deployments using env vars for configuration like the following: `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://$(env:HOST_IP):4317"`.

Because the expansion doesn't happen, traces never arrive at the destination.

### Environment

- OS: macOS
- Architecture: arm64
- Go Version: 1.24
- `autoexporter` version: v0.59.0

### Steps To Reproduce

1. Set up a few env vars for testing:

```
export OTEL_SERVICE_NAME=env-var-test
export OTEL_METRICS_EXPORTER=none
export OTEL_LOGS_EXPORTER=none
export OTEL_TRACES_EXPORTER=otlp
export HOST_IP=127.0.0.1
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://$(env:HOST_IP):4317"
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
```

2. Start an app that uses the `autoexport` package to export traces.

3. Run a simple Collector with the grpc Receiver:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  debug:
    verbosity: basic
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug]
  extensions: [opamp]
```

### Expected behavior

Traces are correctly pushed to the Collector, as the `HOST_IP` env var should be expanded.
